spring.application.name=S3DemoApplication


## We also can add below profile in "run Configuration"--> "arguments" --> Dspring.profile.active=local/dev, then no need to mention in application.properties file
#spring.profiles.active=local
spring.profiles.active=dev